### ISSUE TITLE
SMON on Debian?

### ISSUE THREAD

**Issue by eisengrau** [hap-wi/roxy-wi#239]
Hello,

I have just installed Haproxy-WI on Debian Buster as per manual instructions Is it possible to install SMON as well on the same host? I could only see that there is a RPM package, but no mention for Debian-based systems.

Thank You,

**Comment by Aidaho12** [comment]
Hello

Basically, yes it's possible, but not as package and only after donate

**Comment by Aidaho12** [comment]
After more than a year it has happened! Roxy-WI now in dep packages

**Comment by eisengrau** [comment]
Thank you for the effort! This is good news.
