### ISSUE TITLE
Quotes required around haproxy stats_password to install haproxy/keepalived

### ISSUE THREAD

**Issue by lgrawet** [hap-wi/roxy-wi#276]
Hi,

I have to put quotes around haproxy stats_password (which contains special characters) to manage to install haproxy/keepalived.

Thanks,

Laurent

**Comment by Aidaho12** [comment]
Hi,

So, problem is that you cannot put special characters into the password filed?

**Comment by lgrawet** [comment]
I can enter the password in the webif and use it later to get stats in haproxy.
The problem is with haproxy/keepalived deployment script. I get an error message in a red box about a syntax error. The password is interpreted as a command or argument an I can see it in clear in the error box.

**Comment by Aidaho12** [comment]
Ok, I got it. Will fix it, thank you

**Comment by Aidaho12** [comment]
Could you show me error? I cannot reproduce it

**Comment by lgrawet** [comment]
error: /bin/sh: XXXXX: No such file or directory
    Where XXXXX is my password suffix. It is splitted after "<" special character

**Comment by Aidaho12** [comment]
Finally: https://roxy-wi.org/changelog.py#5_2_4 )

**Comment by lgrawet** [comment]
Many thanks, I will try it!

**Comment by lgrawet** [comment]
Just tried it few days ago and everything is fine now !
