### ISSUE TITLE
Issues with monitoring and metrics

### ISSUE THREAD

**Issue by ascige** [hap-wi/roxy-wi#280]
Hi everyone.
Last week I have installed Roxy-WI from RMP sources, but I have some little problem specially with Monitoring (then SMON, checker, Port scanner) and other issue with Metrics. 
If I try to go to SMON admin panel, software say : "You do not have installed SMON service. Read here how to install SMON service".
I am sure that Smon is installed because, as I say above, I made an installation from RPM.

I have configured, two HaProxy, and I don't have a problem to see stas, etc but if I try to click on Metrics, the message is the same write above : "You do not have installed Metrics service. Read hear how to install Metrics service".
What can I do? Have you some check to suggest?
Regards
Antonio

**Comment by Aidaho12** [comment]
Hi

Yes, it's a bug with the next release will be release fix. As workround you may install haproxy-wi-smon and haproxy-wi-metrics

**Comment by ascige** [comment]
Ok! Thanks a lot!
I'm waiting new version. For now I have installed, as you suggested, two haproxy packets.
