### ISSUE TITLE
No 'Admin Area' visible

### ISSUE THREAD

**Issue by MrHappy** [hap-wi/roxy-wi#282]
I followed the manual installation for Debian.
Everything seems to work fine, but I don´t see the 'Admin Area'.
Opening the users.py in the browser gives me a redirect to the overview.py.

Obviously I´m missing something, but I don't know what....

**Comment by Aidaho12** [comment]
Check an user role it must be superAdmin

**Comment by MrHappy** [comment]
I don´t have the role superAdmin available... :(

**Comment by Aidaho12** [comment]
Yes, you have to check it in database

**Comment by MrHappy** [comment]
Looks like I only have a sqlite3 database. How do I do check/enable it?

**Comment by MrHappy** [comment]
Never mind, I found it... Somewhat... Removed the db and recreated it.. Now it is there.
Thanks!
