### ISSUE TITLE
Fail2Ban still point to old haproxy-wi-*.log and SELINUX context issue

### ISSUE THREAD

**Issue by sonofakatosh** [hap-wi/roxy-wi#283]
Dear Aidaho,
I've found that on new roxy-wi fail2ban service the conf is still looking for the hold naming convention in the logpath
`logpath  = /var/www/haproxy-wi/log/haproxy-wi-*.log`

I've changed it to 
`logpath  = /var/www/haproxy-wi/log/*roxy-wi-*.log`
for backward compatibility and it works.

After fixing that, SELINUX complains that fail2ban is not allowed to access the log files out of the box and needs to fix the contest for allowing fail2ban to interact:
Output from journalctl -xe:

```
ago 03 16:47:27 centos8-hawi setroubleshoot[15785]: SELinux is preventing /usr/libexec/platform-python3.6 from getattr access on the file /var/www/haproxy-wi/log/roxy-wi-20210803.log.
                                                    
                                                    *****  Plugin catchall (100. confidence) suggests   **************************
                                                    
                                                    If you believe that platform-python3.6 should be allowed getattr access on the roxy-wi-20210803.log file by default.
                                                    Then you should report this as a bug.
                                                    You can generate a local policy module to allow this access.
                                                    Do
                                                    allow this access for now by executing:
                                                    # ausearch -c 'fail2ban-server' --raw | audit2allow -M my-fail2banserver
                                                    # semodule -X 300 -i my-fail2banserver.pp
```
After this last modification fail2ban starts correctly from the web gui

Regards
Sonofakatosh

**Comment by Aidaho12** [comment]
Thank you!

Could you send me my-fail2banserver.pp? I can't create policy on my servers :(

**Comment by sonofakatosh** [comment]
Sure! as a matter of fact I needed to create two pp files, the first I used right away, the second pp file (the one with the _2) I had to use after modifying the config file to use the new log file.
[my-fail2banserver.zip](https://github.com/hap-wi/roxy-wi/files/6929430/my-fail2banserver.zip)

**Comment by Aidaho12** [comment]
Cool! thanks a lot, I will update selinux package
