### ISSUE TITLE
Grafana missing important file and directories during installation

### ISSUE THREAD

**Issue by sonofakatosh** [hap-wi/roxy-wi#284]
Dear Aidaho,
after installing grafana and prometheus I've found that the grafana service wasn't starting (prometheus started ok), after digging a bit and installing grafana standalone on a test server I've found that the installation from Roxy-wi does not create:
- the grafana user and its group;
Directories
- /var/lib/grafana
- /var/log/grafana
The config file:
/etc/grafana/grafana.ini

After creating them the service started without any issue.
Hope it helps, regards
Sonofakatosh

**Comment by Aidaho12** [comment]
Hello,
Thank you!
But have you create grafana.ini empty or not? вторник, 03 августа 2021г., 18:24 +03:00 от sonofakatosh  ***@***.*** :

**Comment by sonofakatosh** [comment]
Hello!
I've taken the grafana.ini as is from a clean installation of grafana as standalone, I didn't try to create the empty file and see if the service starts, I can try if you need confirmation

**Comment by Aidaho12** [comment]
It would be great, if you check )

**Comment by sonofakatosh** [comment]
It seems to work event with the /etc/grafana/grafana.ini empty, I was able to start the service, reset the password and login on the 3000 port

**Comment by Aidaho12** [comment]
Cool! Thank you very much

**Comment by sonofakatosh** [comment]
you're welcome
bye!

**Comment by Aidaho12** [comment]
If you find any new bugs, please write me, thanks again :)
