### ISSUE TITLE
Node 'frontend http_in\n' has no position. mv: cannot stat 'map.png': No such file or directory map

### ISSUE THREAD

**Issue by MrHappy** [hap-wi/roxy-wi#286]
Updated today to v5.2.3.0 (from v5.2.1 - I think ;) ) and now I get this error when I want to open the map:
`Node 'frontend http_in\n' has no position. mv: cannot stat 'map.png': No such file or directory map`
My haproxy-config has not changed.
The apache-error-log gives one error
`<localip> - - [16/Aug/2021:17:24:27 +0200] "GET /map2021-08-16.15:24:27.png HTTP/1.1" 404 514 "https://<localip>/app/config.py?serv=<localip>&showMap" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0`
Apparently the map is not created.
What causes this?

**Comment by Aidaho12** [comment]
Nothing has been changed in map function. Check the apache logs

**Comment by MrHappy** [comment]
There was one error in apache-log:
`[Mon Aug 16 17:21:15.939180 2021] [core:notice] [pid 7290:tid 140141516645504] AH00094: Command line: '/usr/sbin/apache2'
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-5i8t2f7v because the default path (/var/www/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.`
That was easily remedied by creating the folder. Still no map...
If nothing has changed there must be something missing on my system, but I followed the manual installation/update by the letter.

**Comment by Aidaho12** [comment]
There is answer, the directory isn't writeble понедельник, 16 августа 2021г., 18:40 +03:00 от MrHappy  ***@***.*** :

**Comment by MrHappy** [comment]
I saw that, so I created the folder and then the error did not appear anymore. Also before that it created a temp-folder so it could do its thing. After creating the folder the file 'fontlist-v330.json' was created. But no map-file...

**Comment by Aidaho12** [comment]
hm... something strange and wrong happened on your enviroment

**Comment by MrHappy** [comment]
How can we figure out what is/went wrong if there are no errors shown/logged?

**Comment by Aidaho12** [comment]
You should it figure out your self or take Enterprise plan

**Comment by MrHappy** [comment]
wow....
