### ISSUE TITLE
roxy-wi-metrics.service fails to start

### ISSUE THREAD

**Issue by lgrawet** [hap-wi/roxy-wi#287]
Hi,

roxy-wi-metrics.service fails to start with the following error. This might be due to database migration from previous version. I must also indicate roxy-wi is currently in sync with git repo ( 5.2.4) because I already migrated to this version before getting access to roxy-wi-metrics.service. Please, tell me whether I need to/can rollback to 5.2.3 tagged release. 

Aug 20 14:45:09 haproxy-wi metrics[383]: Traceback (most recent call last):
Aug 20 14:45:09 haproxy-wi metrics[383]: File "/var/www/haproxy-wi/app/tools/metrics_master.py", line 128, in <module>
Aug 20 14:45:09 haproxy-wi metrics[383]: main()
Aug 20 14:45:09 haproxy-wi metrics[383]: File "/var/www/haproxy-wi/app/tools/metrics_master.py", line 33, in main
Aug 20 14:45:09 haproxy-wi metrics[383]: servers_list.append(serv[0])
Aug 20 14:45:09 haproxy-wi metrics[383]: TypeError: 'Server' object does not support indexing
Aug 20 14:45:09 haproxy-wi systemd[1]: roxy-wi-metrics.service: main process exited, code=exited, status=1/FAILURE
Aug 20 14:45:09 haproxy-wi systemd[1]: Unit roxy-wi-metrics.service entered failed state.
Aug 20 14:45:09 haproxy-wi systemd[1]: roxy-wi-metrics.service failed.

Thanks for your help,

Laurent

**Comment by Aidaho12** [comment]
Hi,

It was wrong... because services are synced with RPM relases... and you may rollback sql.py, it should help

**Comment by lgrawet** [comment]
roxy-wi-metrics.service is OK after roxy-wi version rollback to 5.2.3
