### ISSUE TITLE
Group Dropdown is blank when Adding Provider

### ISSUE THREAD

**Issue by qcomer** [hap-wi/roxy-wi#290]
Hello,

When trying to add a provider the group dropdown is blank. Now, I have configured users and groups so not sure why.
![msedge_yNBUCVSG4R](https://user-images.githubusercontent.com/7622826/132579784-9156fdff-9adc-4705-9218-41abfd64f0ee.png)

**Comment by Aidaho12** [comment]
Hello,

Probably it's a bug. I guess it will be fixed in the next release

**Comment by qcomer** [comment]
That doesnt sorry very..encouraging. When is the next release? Any short-term fix?

**Comment by Aidaho12** [comment]
You can fix it with downloading these files https://github.com/hap-wi/roxy-wi/tree/master/app/templates/include/provisioning

There is roadmap https://roxy-wi.org/changelog.py

**Comment by Aidaho12** [comment]
btw, this issue has been added as a test case, so it shouldn't happen in the future
