### ISSUE TITLE
Provisioning HA-Proxy on SSH creds (password) fails

### ISSUE THREAD

**Issue by auadams** [hap-wi/roxy-wi#295]
When trying to install ha-proxy though the "proxy install" tab i get the following error.

The serves are set up for ssh authentication over user/password and i tested the connection though the "Check" button on the servers page. It apears to not be re-using the password for sudo access for anything on the site.

fatal: [10.1.4.3]: FAILED! => {"msg": "Missing sudo password"}

**Comment by Aidaho12** [comment]
A password isn't re used for sudo. There is notice, that user must have sudo without password
