### ISSUE TITLE
Installation issue on Centos 7

### ISSUE THREAD

**Issue by shchedrin** [hap-wi/roxy-wi#296]
Performed manual installation per [instruction](https://haproxy-wi.org/installation.py#manual)

Got an error at login screen. After passing admin/admin credentials.
`error: instance matching query does not exist: SQL: SELECT "t1"."id", "t1"."username", "t1"."email", "t1"."password", "t1"."role", "t1"."groups", "t1"."ldap_user", "t1"."activeuser", "t1"."user_services", "t1"."last_login_date", "t1"."last_login_ip" FROM "user" AS "t1" WHERE ("t1"."id" IS ?) LIMIT ? OFFSET ? Params: [None, 1, 0] 'NoneType' object has no attribute 'value' `

Database created successfully

![Снимок экрана 2021-10-14 123745](https://user-images.githubusercontent.com/8821222/137292441-ac265a11-bd69-4e28-bdba-b0d4ff271d19.png)

**Comment by Aidaho12** [comment]
It's ok too
