### ISSUE TITLE
Missing file /var/www/haproxy-wi/app/scripts/ansible/roles/docker-users.yml

### ISSUE THREAD

**Issue by Hugh-G-Mungus** [hap-wi/roxy-wi#299]
Under Servers/Proxy installation I select the option to install HAProxy as a Docker container but see a message at the bottom of the page in red:
fatal: [192.168.0.25]: FAILED! => {"reason": "Could not find or access '/var/www/haproxy-wi/app/scripts/ansible/roles/docker-users.yml' on the Ansible Controller."}
I am running version 5.3.1.0

**Comment by Aidaho12** [comment]
Oooops... the file has been uploaded

Thank you
