### ISSUE TITLE
MYSQL ERROR  ./create_db.py

### ISSUE THREAD

**Issue by ariopangarih** [hap-wi/roxy-wi#301]
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups))' at line 1")

**Comment by ariopangarih** [comment]
i found the answer is to change PostgreQL, but should i do it?

**Comment by Aidaho12** [comment]
emm... first of all: hello

PostgreSQL is not supported by Roxy-WI, but if it works under PostgreSQL, it would be nice :)

**Comment by ariopangarih** [comment]
hello there, how can it be fixed in mysql 8?

**Comment by ariopangarih** [comment]
<img width="1440" alt="Screen Shot 2021-11-18 at 15 14 09" src="https://user-images.githubusercontent.com/50353624/142377301-33373e1e-168a-470c-ad75-5f6d57299c19.png">

then it shows error

**Comment by ariopangarih** [comment]
<img width="1440" alt="Screen Shot 2021-11-18 at 15 18 52" src="https://user-images.githubusercontent.com/50353624/142377961-6047cd9b-f3e7-4787-820b-aea72e239ac8.png">

this is my mysql database, thanks for quick responds 👍

**Comment by Aidaho12** [comment]
show me the output of create_db

**Comment by ariopangarih** [comment]
<img width="1440" alt="Screen Shot 2021-11-18 at 15 32 36" src="https://user-images.githubusercontent.com/50353624/142379817-ad8cc4ab-8a96-4d35-bbe8-f7e0a430f3b6.png">

create_db.py output

**Comment by Aidaho12** [comment]
it works for Server version: 10.6.5-MariaDB MariaDB Server

try to update peewee lib

**Comment by ariopangarih** [comment]
i thing there's something change in mysql 8, so it can't use "groups". I install mariadb then it works! Thnaks you so much

**Comment by Aidaho12** [comment]
Probably yes, and you are welcome
