### ISSUE TITLE
WAF Installation did't do anything

### ISSUE THREAD

**Issue by ariopangarih** [hap-wi/roxy-wi#302]
Evening, i have trouble in installing WAF, i sent screenshot
<img width="1440" alt="Screen Shot 2021-11-19 at 16 34 48" src="https://user-images.githubusercontent.com/50353624/142600285-63812732-1c0b-47d1-9d1b-fda701994bad.png">

After wait the installation, it get nothing.

http error_log
<img width="1440" alt="Screen Shot 2021-11-19 at 16 36 54" src="https://user-images.githubusercontent.com/50353624/142600472-1ede9330-799b-4f7b-a0bc-91c824c448da.png">

roxy-wi error_log
<img width="1440" alt="Screen Shot 2021-11-19 at 16 38 31" src="https://user-images.githubusercontent.com/50353624/142600621-bb867945-b495-4b2d-9862-25e93758b3aa.png">

**Comment by Aidaho12** [comment]
Try to install it manually

**Comment by ariopangarih** [comment]
should i run waf.py manually?

**Comment by Aidaho12** [comment]
No, read this https://roxy-wi.org/troubleshooting.py#installation_errors

**Comment by ariopangarih** [comment]
manual installation works but still show 404 error code (in this case we need 403 error code right).

**Comment by ariopangarih** [comment]
i fixed that error, i think there's miss config in before version so i reinstall haproxy. but, the way u tell me to install WAF manually become another problem, when i add new server ( the same server ), the WAF automatically detect installed and i cant install WAF anymore. Do you know how to reset WAF files when it installed manually before? Thanks

**Comment by Aidaho12** [comment]
Remove the waf folder in the haproxy folder and modsec.conf

**Comment by ariopangarih** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/50353624/143008262-707115a9-96c9-4b76-afaa-ef82518dc404.png">

how about this?

**Comment by Aidaho12** [comment]
google it, it is not about Roxy-WI
