### ISSUE TITLE
waf install on Ubuntu LTS system fails

### ISSUE THREAD

**Issue by lucapiccio** [hap-wi/roxy-wi#303]
Hi when try to install waf on Ubuntu haproxy i found that the script doesn't work

It had some mistake inside 
- ligne 15 force a single version ignoring the arguments
VERSION=$(echo 2.1.3| awk -F"-" '{print $1}') 
necessary to change to 
VERSION=$(echo $VERSION| awk -F"-" '{print $1}')

- wrong include apache path 
 APACHE2_INC=/usr/include/httpd/ 
 but the correct is 
 APACHE2_INC=/usr/include/apache2/

- wrong include apr-1 
 APR_INC=/usr/include/apr-1 
 but the correct is 
 APR_INC=/usr/include/apr-1.0

- missing deb in apt repo pcre-devel (in ubuntu the pack name is libpcre3-dev )

- not install libcurl4-nss-dev libyajl-dev that is necessaries for the compilation of waf

I've wrote the patch

**Comment by Aidaho12** [comment]
Thank you, we are going to rewrite WAF installation completely, with your comment

**Comment by Aidaho12** [comment]
Finally! https://roxy-wi.org/changelog.py#5_3_6

**Comment by lucapiccio** [comment]
Thank you, that's great!
I will test it as soon as possible
