### ISSUE TITLE
Cannot Run - Packet Sequence Error from PyMySQL

### ISSUE THREAD

**Issue by aldalen** [hap-wi/roxy-wi#310]
Hello, I have configured the service to run on my Ubuntu 20.04.3 container... and its not initializing. When I load the overview page, I get an endless stream of "error: Packet sequence number wrong - got 1 expected 0" on the page when I try to use it. 

Seems like a multithreaded issue from PyMySQL. 

Installed from the Deb files.

**Comment by Aidaho12** [comment]
Hello,

Seems like yes, try add https://www.python.org/dev/peps/pep-0249/#threadsafety into db_model.py for mysql connections

**Comment by aldalen** [comment]
Hello I tried to add thread safety and the behavior remains.

**Comment by Aidaho12** [comment]
It's sad :( I don't have an idea how it could be fixed now
