### ISSUE TITLE
issue with adding HAProxy nodes

### ISSUE THREAD

**Issue by hsafe** [hap-wi/roxy-wi#311]
Hi We have purchased and successfully installed the roxy-wi with below info:
roxy-wi-5-3.6.0.el7.noarch
roxy-wi-selinux-2-1.noarch
gssproxy-0.7.0-30.el7_9.x86_64
haproxy22-2.2.17-1.el7.ius.x86_64
roxy-wi-checker-2-5.noarch
roxy-wi-portscanner-1-2.noarch
roxy-wi-keep_alive-2-1.noarch
roxy-wi-smon-2-3.noarch
roxy-wi-release-7-2-3.noarch
roxy-wi-metrics-2-0.noarch
-------------------------------------------
Linux haproxy-roxy-0253 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
--------------------------------------------
We tried to follow the guideline in setting up the server and creating account and successfully adding the first HAProxy node to the list. But we encounter the issue that while it can project the stats page of the HAProxy server it does not load the configuration page no matter if we try what. Can you please advise?
![image_2022_01_17T10_50_59_923Z](https://user-images.githubusercontent.com/12583716/149897666-6b0bcd09-e689-4e42-9af4-ebfacc5c184e.png)
![image_2022_01_17T10_51_40_473Z](https://user-images.githubusercontent.com/12583716/149897678-fba003bd-b318-4b4d-81ea-086e14e662e1.png)
![image_2022_01_17T10_52_06_129Z](https://user-images.githubusercontent.com/12583716/149897685-683b140a-5d42-442f-93fd-a1f38270ab52.png)
![Screenshot from 2022-01-18 11-47-41](https://user-images.githubusercontent.com/12583716/149897729-6090d88b-5a74-4561-a154-4e6323ea17d6.png)

**Comment by Aidaho12** [comment]
Hi,

It looks like you use password auth for SSH, try to use SSH keys

**Comment by hsafe** [comment]
Hi Aideho,
Thanks for the response, I am pretty sure we tested both ways ... actually I maintain a watch on the logs and confirm that either ways I see successful procession ...let me get some info shortly

**Comment by hsafe** [comment]
![image_2022_01_22T06_42_06_792Z](https://user-images.githubusercontent.com/12583716/150628263-c8f8a5b7-92f2-4f4c-b4f2-dab8deb02f93.png)

**Comment by hsafe** [comment]
![Screenshot from 2022-01-23 10-36-05](https://user-images.githubusercontent.com/12583716/150668316-db9f5823-011d-4032-8c1d-385bd3f1bb03.png)

**Comment by hsafe** [comment]
What does the above mean perhaps this is the core issue but as stated earlier we have the key-based authentication on

**Comment by hsafe** [comment]
![Screenshot from 2022-01-23 10-48-09](https://user-images.githubusercontent.com/12583716/150668587-cfdea3e3-e5f8-49b7-a1d4-1a9105175366.png)

**Comment by hsafe** [comment]
Why SFTP ?

**Comment by Aidaho12** [comment]
It means that Roxy-WI can't connect via SSH
