### ISSUE TITLE
Can't access to overview.py

### ISSUE THREAD

**Issue by Cyoxite** [hap-wi/roxy-wi#313]
On fresh install Roxy-WI on Ubuntu 20.04 i can't access after login.

When i open address https://my_ip/ and type default login and password admin:admin i have been redirected to /app/ovierview.py and have multiple errors in plain text:

error: invalid literal for int() with base 10: 'None' 
![Screenshot 2022-02-07 at 19-03-07 https 192 168 3 123](https://user-images.githubusercontent.com/65769708/152845798-6650e47f-8c1d-46a2-950e-e246f6d37a88.png)

**In installation process i seen problem with** 
./create_db.py`

**Like:**

root@HaProxy:/var/www/haproxy-wi/app# ./create_db.py
Updating... one more for version 4.0.0
Updating... go to version 4.2.3
Updating... go to version 4.3.2
Updating... go to version 4.4.2
Updating... go to version 4.5.7
Updating... go to version 4.5.8
Updating... go to version 4.5.6
Updating... DB has been updated to version 4.5.9
Updating... DB has been updated to version 5.0.1
Updating... DB has been updated to version 5.1.2
Updating... DB has been updated to version 5.1.3
Updating... DB has been updated to version 5.2.4
Updating... DB has been updated to version 5.2.4-1
An error occurred: UNIQUE constraint failed: role.name
Updating... DB has been updated to version 5.2.5-1
Updating... DB has been updated to version 5.2.5-2
Updating... DB has been updated to version 5.2.5-3
Updating... DB has been updated to version 5.2.6
Updating... DB has been updated to version 5.3.1
Updating... DB has been updated to version 5.3.2
Updating... DB has been updated to version 5.4.0
Updating... DB has been updated to version 5.4.0-1
Updating... DB has been updated to version 5.4.0-2

I always using sudo chown -R www-data:www-data /var/www/haproxy-wi/

**In mail i have this message:**

HaProxy.home : Feb  7 17:38:58 : www-data : user NOT in sudoers ; TTY=unknown ; PWD=/var/www/haproxy-wi/app ; USER=root ; COMMAND=/bin/chown www->

**Comment by Aidaho12** [comment]
Hmm.... Quite strange.
Do you use sqlite as db? Check is everything ok with db, and all table are ok

**Comment by Cyoxite** [comment]
My version is SQLite version 3.31.1 2020-01-27 19:55:54

I delete db and again created using create_db.py and version 5.2.5 successfully added.

root@HaProxy:/var/www/haproxy-wi/app# ./create_db.py
error: <Model: Version> instance matching query does not exist:
SQL: SELECT "t1"."version" FROM "version" AS "t1" LIMIT ? OFFSET ?
Params: [1, 0]
Updating... one more for version 4.0.0
Updating... go to version 4.2.3
Updating... go to version 4.3.2
Updating... go to version 4.4.2
Updating... go to version 4.5.7
Updating... go to version 4.5.8
Updating... go to version 4.5.6
Updating... groups
Updating... DB has been updated to version 4.5.9
Updating... DB has been updated to version 5.0.1
Updating... DB has been updated to version 5.1.2
Updating... DB has been updated to version 5.1.3
Updating... DB has been updated to version 5.2.0
Updating... DB has been updated to version 5.2.4
Updating... DB has been updated to version 5.2.4-1
Updating... DB has been updated to version 5.2.5
Updating... DB has been updated to version 5.2.5-1
Updating... DB has been updated to version 5.2.5-2
Updating... DB has been updated to version 5.2.5-3
Updating... DB has been updated to version 5.2.6
Updating... DB has been updated to version 5.3.1
Updating... DB has been updated to version 5.3.2
Updating... DB has been updated to version 5.3.2
Updating... DB has been updated to version 5.4.0
Updating... DB has been updated to version 5.4.0-1
Updating... DB has been updated to version 5.4.0-2

And have new error at the start.
So, again `chown -R www-data:www-data /var/www/haproxy-wi/` and at this moment i logged and see dashboard.

I think it simple solution working i will testing it further.

In logs i have `Feb 07 20:22:10 'NoneType' object has no attribute 'exec_command' from ` I'll look at it later.
