### ISSUE TITLE
Follow Installation Instructions - Web Page Shows Default Apache

### ISSUE THREAD

**Issue by danfoxley** [hap-wi/roxy-wi#314]
After following installation instructions (Paid Patreon RPM) and what looks to be a successful installation, the default URL/Page loads default Apache page not Roxy-WI, when using FQDN of the host. It loads OK using https://IPAddr

Thanks,
Dan

On:
 Operating System: CentOS Linux 7 (Core)
 CPE OS Name: cpe:/o:centos:centos:7
 Kernel: Linux 3.10.0-1160.53.1.el7.x86_64
 Architecture: x86-64

From:
https://roxy-wi.org/installation.py#rpm

...after installation (CLI output /confirmation below)

"Open in your browser: https://your_ip/ Default login/password are: admin/admin"

https://ServerIP  = OK
https://server.internaldomain.com = Default Apache Page

What is the suggested way to have Roxy-Wi load using the FQDN of the host machine?

**Comment by Aidaho12** [comment]
Try to restart apace and check the folder /etc/apache/conf.d

**Comment by danfoxley** [comment]
Thanks, https://ip  works   https://host.domain.com  does not, after server reboot. Is conf.d the file to "fix"?

**Comment by Aidaho12** [comment]
There is an instruction https://roxy-wi.org/installation.py#apache
