### ISSUE TITLE
Your browser sent a request that this server could not understand. Size of a request header field exceeds server limit.

### ISSUE THREAD

**Issue by abhinavisgood** [hap-wi/roxy-wi#317]
My error log 

[Fri Feb 11 16:37:27.495738 2022] [ssl:warn] [pid 13005:tid 13005] AH01906: haproxy-wi.example.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)                                                                                                                                                               [Fri Feb 11 16:37:27.495757 2022] [ssl:warn] [pid 13005:tid 13005] AH01909: haproxy-wi.example.com:443:0 server certificate does NOT include an ID which matches the server name                                                                                                                                                                [Fri Feb 11 16:37:27.513243 2022] [ssl:warn] [pid 13005:tid 13005] AH01906: haproxy-wi.example.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)                                                                                                                                                               [Fri Feb 11 16:37:27.513265 2022] [ssl:warn] [pid 13005:tid 13005] AH01909: haproxy-wi.example.com:443:0 server certificate does NOT include an ID which matches the server name 

How to fixx this ??

**Comment by Aidaho12** [comment]
First of all: Hello,

To fix this use valid certificate
