### ISSUE TITLE
Haproxy config problem , where to put the public key after uploading the private key 

### ISSUE THREAD

**Issue by abhinavisgood** [hap-wi/roxy-wi#318]
I cannot find the way to upload the public key [air of the private key which we upload in the haproxy user interface , i saw the tutorial and all the user tutorials i have searched  , cannot find , 
i'm saying this because when  i have uploaded the private key and created the server after that when i click the create server it gives out authentication error

**Comment by Aidaho12** [comment]
First of all hello

why do you want to upload a public key? Roxy-WI does not use public keys

**Comment by abhinavisgood** [comment]
> First of all hello
> 
> why do you want to upload a public key? Roxy-WI does not use public keys

But Roxy Wi  , wherever i upload the private key in the ssh credential and then goto create a new server and then when i test that server it shows something NonType error , while authenticating  , is there something more that i need to give for authentication ?

**Comment by abhinavisgood** [comment]
> First of all hello
> 
> why do you want to upload a public key? Roxy-WI does not use public keys

I am really sorry if it sounds rude but , ihave tried installing the haproxy-wi user interface and mostly failed at this step of creating servers. It would be really helpful of you if you could help me out with this  .

**Comment by abhinavisgood** [comment]
I don't want to use ssh keys for connection , instead i want to use only the passsword based , method  , is that possible, ? if so then 
how ?

**Comment by Aidaho12** [comment]
Just uncheck SSH key
