### ISSUE TITLE
Cannot connect to HAProxy

### ISSUE THREAD

**Issue by ripplethor** [hap-wi/roxy-wi#319]
I can read the config file and view the stats, but the overview shows haproxy not online.

haproxy 
Cannot get information about HAProxy Last edit: Mar 21 06:18

**Comment by Aidaho12** [comment]
Have you configured sock port for HAProxy?

**Comment by ripplethor** [comment]
I have set the socks setting in the global section, but have no idea about socks port?

stats socket /run/haproxy/admin.sock mode 660 level admin

**Comment by Aidaho12** [comment]
Have you read this https://roxy-wi.org/howto.py?howto=stats_pages#haproxy_config ?
