### ISSUE TITLE
New HA cluster: haproxy never gets installed on slave server

### ISSUE THREAD

**Issue by lgrawet** [hap-wi/roxy-wi#320]
Hi,

When creating a new HA cluster, the dialog keeps running forever. HAProxy never gets installed on slave server. There is no evidence of such attempt in roxy-wi.log or ansible.log. Logging only concerns the main server.

![image](https://user-images.githubusercontent.com/10059091/164472978-a2f97b58-80fb-4e2e-9403-13e70374cb74.png)

Best regards,

Laurent

**Comment by Aidaho12** [comment]
btw, fix is already here https://github.com/hap-wi/roxy-wi/blob/master/inc/ha.js

**Comment by lgrawet** [comment]
Hi @Aidaho12,

I've patched my version with the fix, deployed on three HA setups,  works fine !

Thanks !
