### ISSUE TITLE
Unable to select SSL HAProxy certificate for listener

### ISSUE THREAD

**Issue by sethwhitworth** [hap-wi/roxy-wi#330]
When trying to create a SSL Listener in HAProxy, you are unable to select a certificate file. When you type a certificate name the dropdown states "Select a server first".

There is an issue in add.js causing it to look for the wrong server.

Line 884 needs to be changed from 
```if(!checkIsServerFiled('#serv')) return false;```
```if(!checkIsServerFiled('#serv2')) return false;```

**Comment by Aidaho12** [comment]
Thank you, it's fixed
