### ISSUE TITLE
Problem with create_db.py and so the connection

### ISSUE THREAD

**Issue by Rod0lphe** [hap-wi/roxy-wi#335]
I execute the script for creation database but then the database is empty. See below :

----------------------

`proxy@haproxy:/var/www/haproxy-wi/app$ sudo ./create_db.py 
Updating... DB has been updated to version 5.1.3
Updating... DB has been updated to version 5.2.4
Updating... DB has been updated to version 5.2.4-1
Updating... DB has been updated to version 5.2.5-1
Updating... DB has been updated to version 5.2.5-2
Updating... DB has been updated to version 5.2.5-3
Updating... DB has been updated to version 5.2.6
Updating... DB has been updated to version 5.3.1
Updating... DB has been updated to version 5.3.2
Updating... DB has been updated to version 5.4.2
Updating... DB has been updated to version 5.4.3
Updating... DB has been updated to version 5.4.3-1
Updating... DB has been updated to version 6.0.0.0
Updating... DB has been updated to version 6.0.0.0-1
proxy@haproxy:/var/www/haproxy-wi/app$ mysql -u roxy-wi -p roxywi
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 61
Server version: 10.6.7-MariaDB-2ubuntu1.1 Ubuntu 22.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [roxywi]> show tables;
Empty set (0.001 sec)

MariaDB [roxywi]> `

-----------------------

And so I can't connect to the interface.
Thank you in advance

**Comment by Aidaho12** [comment]
have you set mysql in roxy-wi.cfg?

**Comment by Rod0lphe** [comment]
@Aidaho12 Yes as requested below :

[mysql]
#Enable MySQL DB. Default will be used Sqlite DB. Default disable</li>
enable = 1
mysql_user = roxywi
mysql_password = roxy-wi
mysql_db = roxywi
mysql_host = 127.0.0.1

**Comment by Rod0lphe** [comment]
I fixed a few things and here is my execution of create.py :

`reverseproxy@haproxy:/var/www/haproxy-wi/app$ sudo ./create_db.py
Content-type: text/html

<center><div class="alert alert-danger">Check the config file. Presence section configs and parameter haproxy_save_configs_dir</div>
Content-type: text/html

<center><div class="alert alert-danger">Check the config file. Presence section mysql and parameter enable</div>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
  File "/usr/lib/python3/dist-packages/peewee.py", line 3432, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/./create_db.py", line 1048, in <module>
    create_tables()
  File "/var/www/haproxy-wi/app/db_model.py", line 565, in create_tables
    with conn:
  File "/usr/lib/python3/dist-packages/peewee.py", line 3064, in __enter__
    self.connect()
  File "/usr/lib/python3/dist-packages/peewee.py", line 3095, in connect
    with __exception_wrapper__:
  File "/usr/lib/python3/dist-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3/dist-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
  File "/usr/lib/python3/dist-packages/peewee.py", line 3432, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file`


However pewee is installed

**Comment by Aidaho12** [comment]
it looks like Roxy-WI can't find the config file. it must be in /etc/roxy-wi

**Comment by Rod0lphe** [comment]
Ok, it's impossible to install : 

roxy-wi roxy-wi-checker roxy-wi-metrics roxy-wi-smon roxy-wi-portscanner roxy-wi-keep-alive roxy-wi-socket

I did add the repo

**Comment by Aidaho12** [comment]
any errors?

**Comment by Rod0lphe** [comment]
Is this mandatory?

![image](https://user-images.githubusercontent.com/95852118/188131165-6852210d-55c0-437c-8f0d-1f75beff345b.png)

**Comment by Aidaho12** [comment]
Yes

**Comment by Rod0lphe** [comment]
@Aidaho12 I have to transfer a login/password to you where? This system will be in production...

**Comment by Aidaho12** [comment]
No, you will get the credentials, when you pay for it. There are all information on the site, please, read carefully

**Comment by Rod0lphe** [comment]
Ok but I saw that without using RPM it was free.

![image](https://user-images.githubusercontent.com/95852118/188157600-180822d2-c2ab-4b3c-b0c4-bb2edbde0a94.png)

However, I did all the installation in manual but I miss the /etc/roxy-wi

**Comment by Aidaho12** [comment]
Yes, it's a free if you install it from git

**Comment by Rod0lphe** [comment]
So that's what I did but I don't have the file I need in /etc/roxy-wi

My error when I read the create_db.py comes from that

**Comment by Aidaho12** [comment]
create the folder, and move the file to it. reread the instruction there are these steps

**Comment by Rod0lphe** [comment]
I have access to the interface but to check, auto-start, etc. in the update menu you just have to add apache or www-data to sudoers?

**Comment by Aidaho12** [comment]
Auto start does not work in the free version

**Comment by Rod0lphe** [comment]
I just want to manage HAproxy with your interface but I don't have access to the Haproxy/Addproxy menu. Maybe add.py ?

**Comment by Aidaho12** [comment]
It's not clear for me? A page for creating proxy configuration for HAProxy add.py, yes
