### ISSUE TITLE
Apache not starting/restaring from roxywi 

### ISSUE THREAD

**Issue by AnupHST** [hap-wi/roxy-wi#337]
Hello,
I have to install roxywi on centos 7 
I have an issue, when I try to restart apache from Roxy panel it's shows

[
error: instance matching query does not exist: SQL: SELECT `t1`.`id`, `t1`.`server_id`, `t1`.`os_info`, `t1`.`sys_info`, `t1`.`cpu`, `t1`.`ram`, `t1`.`disks`, `t1`.`network` FROM `system_info` AS `t1` WHERE (`t1`.`server_id` = %s) LIMIT %s OFFSET %s Params: [12, 1, 0] in function: select_os_info in file: sql.py 
]

But haproxy restart/start working fine from Roxy panel

![image](https://user-images.githubusercontent.com/73455995/191032836-a503fe80-8581-47f8-9234-4ae40d3d728b.png)

@Aidaho12 
Have any suggestions?

Thank you

**Comment by Aidaho12** [comment]
Hello,

Looks like you had added server with wrong credentials, and fixed it after. Try to open server info on the Servers tab

**Comment by Anup1592** [comment]
Hello,
When I add a server with credentials it shows "connect is accepted"
![image](https://user-images.githubusercontent.com/73455995/191159658-066001c2-3a94-43e4-970e-5d833dff2456.png)

But still the same issue

Thank you so much

**Comment by Aidaho12** [comment]
not now wrong credentials, but when you created server. Ok. nevermind, just press the system info button and check restarting again

**Comment by Anup1592** [comment]
Hello,
still the same issue,
Can you check if I can share the details or any other solution?

Thank you

**Comment by Aidaho12** [comment]
Does Roxy-WI show the server info?

**Comment by Anup1592** [comment]
No, Roxy-WI does not show server info
![image](https://user-images.githubusercontent.com/73455995/191209177-3800dcb6-dd13-4760-bf19-e253db10b483.png)
