### ISSUE TITLE
KeepAlived - Cannot get Keepalived Status

### ISSUE THREAD

**Issue by jeremypascaud** [hap-wi/roxy-wi#340]
Hello,
How is VRRP status checked ?
I have an error : Cannot get Keepalived Status

**Comment by Aidaho12** [comment]
Hello

It takes status from systemctl.

To understand happens check the logs

**Comment by jeremypascaud** [comment]
Hello,

I have error many error for determine Mysql version, is this the cause ?

[Wed Oct 12 09:10:23.580851 2022] [cgi:error] [pid 19195] [client X.X.X.X:50324] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.580966 2022] [cgi:error] [pid 19195] [client X.X.X.X:50324] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.581138 2022] [cgi:error] [pid 21956] [client X.X.X.X:50322] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.581220 2022] [cgi:error] [pid 21956] [client X.X.X.X:50322] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.706844 2022] [cgi:error] [pid 15083] [client X.X.X.X:50323] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.706942 2022] [cgi:error] [pid 15083] [client X.X.X.X:50323] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.927830 2022] [cgi:error] [pid 14452] [client X.X.X.X:50325] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.927913 2022] [cgi:error] [pid 14452] [client X.X.X.X:50325] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.931547 2022] [cgi:error] [pid 8031] [client X.X.X.X:50321] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:23.931677 2022] [cgi:error] [pid 8031] [client X.X.X.X:50321] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:24.089224 2022] [cgi:error] [pid 19195] [client X.X.X.X:50324] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://SERVERNAME/app/hapservers.py?service=keepalived
[Wed Oct 12 09:10:24.089328 2022] [cgi:error] [pid 19195] [client X.X.X.X:50324] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://SERVERNAME/app/hapservers.py?service=keepalived

**Comment by Aidaho12** [comment]
No, it does not influence
