### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by artkrp31** [hap-wi/roxy-wi#342]
Installed Roxy-WI in manual mode, everything went without errors.
Nothing happens after trying to log in.
Please advise what is the problem?

**Comment by GitGud241** [comment]
Hello!

I also have the same problem. 

When I check the console I get the following error.

POST https://mylocalip/app/login.py 500 (Internal Server Error)

The packages in the installation manual are all installed and updated and I have followed the steps for Ubuntu. I'm using ubuntu 22.04 LTS.

Thank you for any support :)

**Comment by Aidaho12** [comment]
First of all check logs. Without logs I can't say something
