### ISSUE TITLE
Fresh manual install cannot login 

### ISSUE THREAD

**Issue by nomadtechiemike** [hap-wi/roxy-wi#345]
Hi just wanted to test out the sript before I consider buying a subscription.

I have added a DB and rund the DB script, when i goto the login page and enter admin/admin nothing happens

I checked the console log and see: 
Firefox can’t establish a connection to the server at wss://192.168.1.66/. reconnecting-websocket.js:1:1075
The connection to wss://192.168.1.66/ was interrupted while the page was loading.

In MS Edge I see 
[error] undefined login.py:1  Failed to load resource: the server responded with a status of 500 (Internal Server Error)
login.py:1  Failed to load resource: the server responded with a status of 500 (Internal Server Error)
reconnecting-websocket.js:1         
       WebSocket connection to 'wss://192.168.1.66/' failed: Error during WebSocket handshake: Unexpected response code: 503

all the .py files have 755 and are owned by apache:apache

**Comment by nomadtechiemike** [comment]
Hi no I am using Ubuntu

**Comment by nomadtechiemike** [comment]
Hi no I am using Ubuntu


Sent with Proton Mail secure email.

------- Original Message -------

**Comment by Aidaho12** [comment]
Then why apache user? There is no this user on Ubuntu

**Comment by nomadtechiemike** [comment]
As per the install instructions ?

sudo chown -R apache:apache /var/www/haproxy-wi/



Sent with Proton Mail secure email.

------- Original Message -------

**Comment by nomadtechiemike** [comment]
The instructions for manual install are not clear - you need to change it


#### Install required dependencies

apt-get install apache2 python3 python3-pip python3-ldap rsync ansible python3-requests \
python3-networkx python3-matplotlib python3-bottle python3-future python3-jinja2 python3-peewee \
python3-pymysql netcat nmap net-tools lshw dos2unix libapache2-mod-wsgi-py3 openssl sshpass -y

Then this

$ cd /var/www/
$ git clone https://github.com/hap-wi/roxy-wi.git /var/www/haproxy-wi


$ sudo chown -R www-data:www-data haproxy-wi/

$ sudo cp haproxy-wi/config_other/httpd/roxy-wi_deb.conf /etc/apache2/sites-available/roxy-wi.conf

$ sudo a2ensite roxy-wi.conf

$ sudo a2enmod cgid ssl proxy_http rewrite

$ sudo pip3 install -r haproxy-wi/config_other/requirements_deb.txt

$ sudo systemctl restart apache2



Sent with Proton Mail secure email.

------- Original Message -------

**Comment by nomadtechiemike** [comment]
Missing cmd here

/var/www$ sudo mkdir /var/lib/roxy-wi/keys/
mkdir: cannot create directory '/var/lib/roxy-wi/keys/': No such file or directory

need to run

cd /var/lib/

sudo mkdir roxy-wi






Sent with Proton Mail secure email.

------- Original Message -------

**Comment by nomadtechiemike** [comment]
another typo - this is not required as it already exists

sudo mkdir /var/www/haproxy-wi/app/certs/

after this command
sudo mkdir /etc/roxy-wi/

need to run cd /etc/www/

before running
sudo mv haproxy-wi/roxy-wi.cfg /etc/roxy-wi



Sent with Proton Mail secure email.

------- Original Message -------

**Comment by nomadtechiemike** [comment]
sorry cd /var/www/


Sent with Proton Mail secure email.

------- Original Message -------

**Comment by nomadtechiemike** [comment]
before this cmd
sudo chown -R apache:apache /var/www/haproxy-wi/

need to run

as root
adduser apache


Sent with Proton Mail secure email.

------- Original Message -------

**Comment by nomadtechiemike** [comment]
Not sure what you mean by this?

If you use Debian/Ubuntu:

Change httpd to apache2 PATH and apache to www-data user in all configs


Sent with Proton Mail secure email.

------- Original Message -------

**Comment by Aidaho12** [comment]
Because there is no apache user on Ubuntu:)

Please, read how it works on Ubuntu

**Comment by nomadtechiemike** [comment]
So these comands  sudo chown -R apache:apache  should be sudo chown -R www-data:www-data ?




Sent with Proton Mail secure email.

------- Original Message -------

**Comment by Aidaho12** [comment]
Yes

**Comment by nomadtechiemike** [comment]
Please update the instructions or add that information at the top for ubuntu run sudo chown -R www-data:www-data rather than after the commands

Ok I tried a fresh install and get 500 internal server error

this is my error log

File "/var/www/haproxy-wi/app/overview.py", line 10, in <module>    import modules.roxywi.logs as roxy_logs
  File "/var/www/haproxy-wi/app/modules/roxywi/logs.py", line 4, in <module>
    import modules.server.server as server_mod
  File "/var/www/haproxy-wi/app/modules/server/server.py", line 6, in <module>
    from modules.server import ssh_connection
  File "/var/www/haproxy-wi/app/modules/server/ssh_connection.py", line 1, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/overview.py", line 10, in <module>
    import modules.roxywi.logs as roxy_logs
  File "/var/www/haproxy-wi/app/modules/roxywi/logs.py", line 4, in <module>
    import modules.server.server as server_mod
  File "/var/www/haproxy-wi/app/modules/server/server.py", line 6, in <module>

I have run pip3 install paramiko


Sent with Proton Mail secure email.

------- Original Message -------

**Comment by nomadtechiemike** [comment]
Just tried a fresh install on CentOS 8 

No match for argument: python3-paramiko
No match for argument: ansible
Package libmodulemd-2.13.0-1.el8.x86_64 is already installed.
Error: Unable to find a match: python3-paramiko ansible

**Comment by Aidaho12** [comment]
Probably it's because you have not install epel repo
