### ISSUE TITLE
debian/ubuntu: lorotate config conflict.

### ISSUE THREAD

**Issue by lgrawet** [hap-wi/roxy-wi#354]
Hi,

In debian/ubuntu, the package manager already provides an `/etc/logrotate.d/haproxy` config file with the following content:
```
/var/log/haproxy.log {
    daily
    rotate 52
    missingok
    notifempty
    compress
    delaycompress
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}
```

The file deployed with roxy-wi `/etc/logrotate.d/haproxy.conf` is conflicting with the one from the package and prevents logrotate unit to start:
```
error: haproxy.conf:1 duplicate log entry for /var/log/haproxy.log
```

Moreover, the debian/ubuntu config makes use of the rsyslog-rotate script. So the roxy-wi config should not be deployed at all on those platforms.

Best regards,

Laurent

**Comment by Aidaho12** [comment]
Hi,

Thank you, will disable it

**Comment by Aidaho12** [comment]
It fixed https://github.com/hap-wi/roxy-wi/commit/0054f25da7cf8c7480452f48e39308b5e392dc67#diff-e307041c1394eafdf34498419185ed3cb7d45294f56e3ea0b32fc9416672cd9e
