### ISSUE TITLE
Error on manual install step sudo ./create_db.py

### ISSUE THREAD

**Issue by alvic2000** [hap-wi/roxy-wi#359]
Good day!
After step sudo ./create_db.py I receive nex error:

sudo ./create_db.py
too many SQL variables
<Model: Version> instance matching query does not exist:
SQL: SELECT "t1"."version" FROM "version" AS "t1" LIMIT ? OFFSET ?
Params: [1, 0]
Updating... DB has been updated to version 6.0.0.0
Updating... DB has been updated to version 6.0.0.0-1
Updating... DB has been updated to version 6.2.2.0
Updating... DB has been updated to version 6.3.4.0
Updating... DB has been updated to version 6.3.5.0
Updating... DB has been updated to version 6.3.6.0
Updating... DB has been updated to version 6.3.8
Updating... DB has been updated to version 6.3.9
Updating... DB has been updated to version 6.3.11
Updating... DB has been updated to version 6.3.12
Updating... DB has been updated to version 6.3.13
Updating... DB has been updated to version 6.3.13-1
Updating... DB has been updated to version 6.3.13-2
An error occurred: table smon__tmp__ has no column named UNIQUE

Is it normal?

P.S. I can to login to https://your_ip/
P.P.S. Some details:

OS - CentOS 8 Stream (x86_64)

cat /etc/roxy-wi/roxy-wi.cfg
[main]
'# Path to the files destination
fullpath = /var/www/haproxy-wi
log_path = /var/log/roxy-wi
lib_path = /var/lib/roxy-wi

[configs]
'# Folders for configs
haproxy_save_configs_dir = ${main:lib_path}/configs/hap_config/
kp_save_configs_dir = ${main:lib_path}/configs/kp_config/
nginx_save_configs_dir = ${main:lib_path}/configs/nginx_config/
apache_save_configs_dir = ${main:lib_path}/configs/apache_config/

[mysql]
'# By default Sqlite DB is used
enable = 0
mysql_user = roxy-wi
mysql_password = roxy-wi
mysql_db = roxywi
mysql_host = 127.0.0.1
mysql_port = 3306

**Comment by Aidaho12** [comment]
Hi,

It is not ok, but Roxy-WI will work

**Comment by alvic2000** [comment]
Next try to start command  ./create_db.py  show nex error:
./create_db.py
too many SQL variables
Updating... DB has been updated to version 6.0.0.0
Updating... DB has been updated to version 6.0.0.0-1
Updating... DB has been updated to version 6.2.2.0
Updating... DB has been updated to version 6.3.4.0
Updating... DB has been updated to version 6.3.5.0
Updating... DB has been updated to version 6.3.6.0
Updating... DB has been updated to version 6.3.8
Updating... DB has been updated to version 6.3.9
Updating... DB has been updated to version 6.3.11
Updating... DB has been updated to version 6.3.12
Updating... DB has been updated to version 6.3.13
Updating... DB has been updated to version 6.3.13-1
Updating... DB has been updated to version 6.3.13-2
An error occurred: table smon__tmp__ has no column named UNIQUE

**Comment by Aidaho12** [comment]
I've checked it. It is not a bug, just error which does not affect work

**Comment by alvic2000** [comment]
![Error jpg](https://github.com/hap-wi/roxy-wi/assets/96197160/b7ac634f-60d9-44d2-ad69-c4ba63c776e5)
Here I see UNIQUE - is it not connected with previosly posted error?

**Comment by Aidaho12** [comment]
No, this error means that you have a server with the same IP address

**Comment by alvic2000** [comment]
Ok, thank you.
