### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by brutherford1981** [hap-wi/roxy-wi#361]
Seems to be a bug in LDAP authentication - I can't seem to get it to work with AD - spins and spins and spins and no results

Authenticating against a Windows Server 2022 machine, ldap3 module works fine, ldPlease advise.... I'm 99% of the way there.

**Comment by Aidaho12** [comment]
It works fine. Check the logs, probably there is an answer

**Comment by brutherford1981** [comment]
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/options.py", line 723, in <module>
    roxywi_user.get_ldap_email()
  File "/var/www/haproxy-wi/app/modules/roxywi/user.py", line 219, in get_ldap_email
    bind = ldap_bind.simple_bind_s(user, password)
  File "/usr/local/lib/python3.10/dist-packages/ldap/ldapobject.py", line 248, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/local/lib/python3.10/dist-packages/ldap/ldapobject.py", line 242, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/local/lib/python3.10/dist-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'errno': 107, 'ctrls': [], 'info': 'Error in the pull function.'}

server is not down - works just fine via LDAPsearch.

**Comment by Aidaho12** [comment]
Does Ldapsearch work on the Roxy-WI server? Also there is could be problems with port, ssl settings

**Comment by brutherford1981** [comment]
Figured it out, the connection string in users.py had a small error.

Cheers!

-B

Brett Ian Rutherford
***@***.***> | Cell<tel:740.424.5620> | LinkedIn<https://www.linkedin.com/in/brettianrutherford> | Blog<https://www.brettrutherford.com>
________________________________

**Comment by Aidaho12** [comment]
Could you say what the strings and more about the small error?

**Comment by brutherford1981** [comment]
What was preventing this from being used as is - is a bug in the logic for "ldaps type" which always defaulted it to ldaps which wouldn't work in my environment - i set ldap to always be ldap and that works fine

Now I'm running into an issue where any known user basically can log in with any password, and I'm at my wits end trying to solve it.
