### ISSUE TITLE
500 Internal server error CentOS 7

### ISSUE THREAD

**Issue by HoroshoVse** [hap-wi/roxy-wi#362]
После ручной установки на CentOS 7 в браузере появляется данная ошибка, причем сначала на долю секунды появляется начальный синий экран панели.
<img width="1050" alt="Снимок экрана 2023-09-30 в 12 48 36" src="https://github.com/hap-wi/roxy-wi/assets/127848249/a3acd1d5-6ab2-4d82-8eeb-e3c811118001">
Все пакеты установились без ошибок. В логах ничего критичного вроде бы нет.
<img width="1097" alt="Снимок экрана 2023-09-30 в 12 49 13" src="https://github.com/hap-wi/roxy-wi/assets/127848249/8dc1d053-4a29-4f97-88ea-58fdf99e8b6e">

Прошу помощи.

**Comment by Aidaho12** [comment]
Есть что-нибудь в roxy-wi-error.log?

**Comment by HoroshoVse** [comment]
В директории /var/log/roxy-wi/ пусто

**Comment by Aidaho12** [comment]
Посмотрите в директории апача

**Comment by HoroshoVse** [comment]
Пишет что нет модуля Flask
<img width="545" alt="Снимок экрана 2023-09-30 в 16 02 52" src="https://github.com/hap-wi/roxy-wi/assets/127848249/8abcb296-cc10-461d-a965-578157fa7f90">
Но по факту он установлен
<img width="1272" alt="Снимок экрана 2023-09-30 в 16 03 30" src="https://github.com/hap-wi/roxy-wi/assets/127848249/638ed7cf-18e4-47da-9418-8cba8334d20c">

**Comment by Aidaho12** [comment]
из под пользователя apache flask доступен?

**Comment by HoroshoVse** [comment]
Не совсем понял как это проверить. Буду благодарен если подскажите.

**Comment by Aidaho12** [comment]
Примерно так:
```
su - apache
python3 
import flask
```

**Comment by HoroshoVse** [comment]
Именно так делал, но подумал что вы имели в виду что то другое
При попытке переключится на пользователя apache
<img width="543" alt="Снимок экрана 2023-10-01 в 01 13 33" src="https://github.com/hap-wi/roxy-wi/assets/127848249/3f217e4c-cfe7-4bf0-b999-7bb334c4cce1">
хотя в списке он есть
<img width="460" alt="Снимок экрана 2023-10-01 в 01 14 09" src="https://github.com/hap-wi/roxy-wi/assets/127848249/50a87a60-5cbe-4b30-a7a0-79e489d4ee2c">

**Comment by Aidaho12** [comment]
Тогда сложно сказать, попробуйте обновить пип, потом фласк

**Comment by Deadder** [comment]
I have the same issue on a brand new box running EL9, installing from RPM repo - pip and flask are updated to newest already. Even creating the DB results in this weird flask behavior:
```
File "/var/www/haproxy-wi/app/./create_db.py", line 4, in <module>
    from modules.db.db_model import *
  File "/var/www/haproxy-wi/app/modules/db/db_model.py", line 4, in <module>
    from flask_login import UserMixin
  File "/usr/local/lib/python3.9/site-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.9/site-packages/flask_login/login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
```

Thats the error I see on DB creation, page execution, etc.

No idea what to do to resolve. Feels like maybe a missing dependency or something, but just not sure what to check next.

Thanks for any help!

**Comment by Aidaho12** [comment]
Looks like there is a problem with flask depends. Could you show flask version and werkzeug?

**Comment by Deadder** [comment]
Sure
```
$ flask --version
Python 3.9.16
Flask 3.0.0
Werkzeug 3.0.0
```

**Comment by Aidaho12** [comment]
Try to install these versions:
 
Werkzeug==2.2.3
Flask==2.2.5
Flask-Login==0.6.2
Flask-APScheduler==1.13.0
Flask-Caching==2.1.0

**Comment by Deadder** [comment]
> Try to install these versions:   Werkzeug==2.2.3 Flask==2.2.5 Flask-Login==0.6.2 Flask-APScheduler==1.13.0 Flask-Caching==2.1.0

That did it! I guess the v3 that installs as "latest" isn't compatible yet.

Thanks!
