### ISSUE TITLE
URL rewrite needs updated on HAProxy > Overview > Backends

### ISSUE THREAD

**Issue by ziptx** [hap-wi/roxy-wi#369]
When clicking the hyper linked backends on the following URL:  
https://10.1.1.1/app/service/haproxy

The URL's write to this:  https://10.1.1.1/app/config/section/10.1.1.2/backend%20per_ip_rates 
and causes a "405 Method Not allowed: The method is not allowed for the requested URL." (with the OOPS robot).

The correct URL would be: https://10.1.1.1/app/config/section/haproxy/10.1.1.2/backend%20per_ip_rates   (notice 'haproxy' part)

Roxy-WI version 7.0.2.0

**Comment by Aidaho12** [comment]
Thank you. Will be fixed in the next release
