### ISSUE TITLE
HAProxy log files not rotated

### ISSUE THREAD

**Issue by lgrawet** [hap-wi/roxy-wi#371]
Hi,

You are pushing with ansible an /etc/rsyslog.d/49-haproxy.conf file which splits haproxy logging in 3 files : acces.log, error.log and status.log.
The problem is your logrotate config refers to /var/log/haproxy.log which doesn't exist.
The second potential problem is logrotate config is not pushed to Debian/Ubuntu because of #354 

If you modify your logrotate script to only manage those three files and not haproxy.log anymore, it could be pushed again to Debian/Ubuntu along with /etc/logrotate.d/haproxy from the deb packaging system. You should then choose a meaningful name other than haproxy.conf. Why not happroxy-roxy.conf?

Thanks,

Laurent

**Comment by Aidaho12** [comment]
Hi, thank you. It will be fixed in the next release

**Comment by Aidaho12** [comment]
And it fixed
